### PR TITLE
Lightweight Kprove - 2

### LINKED ISSUE #1333: Low overhead for `kprove` (call `kompile` ahead of time)
File `demo.k`
```
module DEMO
  imports DOMAINS
  configuration <k> .K </k>
endmodule

module EXTENDED
  imports DEMO
  configuration <extended> <k/> </extended>
endmodule
```

File `extended-bad-module-spec.k`
```
requires "demo.k"

module VERIFICATION-DEMO
    imports DEMO
endmodule

module VERIFICATION-EXTENDED
    imports EXTENDED
    imports VERIFICATION-DEMO
endmodule

module EXTENDED-BAD-MODULE-SPEC
    imports VERIFICATION-EXTENDED

    rule <k> .K => ?_ </k>
endmodule
```
File `Makefile`
```
DEF=extended
EXT=test
TESTDIR=.
KOMPILE_BACKEND=haskell
KPROVE_FLAGS=--def-module VERIFICATION-DEMO

export KOMPILE_BACKEND
export KPROVE_FLAGS

include ../../../include/kframework/ktest.mak
```

### LINKED ISSUE #1887: [Bug] [kprove] - Failure with NullPointerException when building ProofDefinition
K Version
---------

```
$ kompile --version
RV-K version 1.0-SNAPSHOT
Git revision: 14483d1
Git branch: UNKNOWN
Build date: Fri Mar 26 21:50:06 UTC 2021
```

Description
-----------

Running `kprove` on a definition crashes when building the specification definition with an uninformative error message.

Input Files
-----------

The input `kmcd-gen.k`:

```
module FIXED-INT
  imports INT
  imports BOOL
  syntax FInt  ::=
    "(" FInt ")" [bracket]
  | "FInt" "(" value: Int "," one: Int ")" [klabel(FInt), symbol]
  syntax Int  ::=
    "baseFInt" "(" FInt ")" [function, klabel(baseFInt)]
  | "decimalFInt" "(" FInt ")" [function, klabel(decimalFInt)]
  rule baseFInt(FI) => value(FI) /Int one(FI)
  rule decimalFInt(FI) => value(FI) %Int one(FI)
  syntax FInt  ::=
    "0FInt" "(" Int ")"
  | "1FInt" "(" Int ")"
  rule 0FInt(ONE) => FInt(0  , ONE)  [macro]
  rule 1FInt(ONE) => FInt(ONE, ONE)  [macro]
  syntax FInt  ::=
    FInt "*FInt" FInt [function]
  | FInt "/FInt" FInt [function]
  | FInt "^FInt" Int [function]
  > FInt "+FInt" FInt [function]
  | FInt "-FInt" FInt [function]
  rule FInt(VALUE1, ONE1) *FInt FInt(VALUE2, ONE2) => FInt((VALUE1 *Int VALUE2) /Int ONE2             , ONE1)
  rule FInt(VALUE1, ONE1) /FInt FInt(VALUE2, ONE2) => FInt((VALUE1 *Int ONE2) /Int VALUE2             , ONE1) requires VALUE2 =/=Int 0
  rule FInt(VALUE1, ONE1) +FInt FInt(VALUE2, ONE2) => FInt(VALUE1 +Int ((VALUE2 *Int ONE1) /Int ONE2) , ONE1)
  rule FInt(VALUE1, ONE1) -FInt FInt(VALUE2, ONE2) => FInt(VALUE1 -Int ((VALUE2 *Int ONE1) /Int ONE2) , ONE1)
  rule FInt( VALUE, ONE) ^FInt E => FInt((VALUE ^Int E) /Int (ONE ^Int (E -Int 1)), ONE)          requires E  >Int 0
  rule FInt(_VALUE, ONE) ^FInt E => 1FInt(ONE)                                                    requires E ==Int 0
  rule FInt( VALUE, ONE) ^FInt E => FInt((ONE ^Int (1 -Int E)) /Int (VALUE ^Int (0 -Int E)), ONE) requires E  <Int 0
  syntax Bool  ::=
    FInt "<FInt" FInt [function]
  | FInt "<=FInt" FInt [function]
  | FInt ">FInt" FInt [function]
  | FInt ">=FInt" FInt [function]
  | FInt "==FInt" FInt [function]
  | FInt "=/=FInt" FInt [function]
  rule FInt(VALUE1, ONE1)   <FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2   <Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  <=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  <=Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)   >FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2   >Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  >=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  >=Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1)  ==FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2  ==Int VALUE2 *Int ONE1
  rule FInt(VALUE1, ONE1) =/=FInt FInt(VALUE2, ONE2) => VALUE1 *Int ONE2 =/=Int VALUE2 *Int ONE1
endmodule

module KMCD-DATA
  imports BOOL
  imports FIXED-INT
  imports MAP
endmodule

module KMCD-DRIVER
  imports KMCD-DATA
  imports MAP
  imports STRING
  configuration <kmcd-driver>
          <k> $PGM:MCDSteps </k>
          <return-value> .K </return-value>
          <msg-sender> 0:Address </msg-sender>
          <this> 0:Address </this>
          <current-time> 0:Int </current-time>
          <call-stack> .List </call-stack>
          <pre-state> .K </pre-state>
          <events> .List </events>
          <tx-log> .Transaction </tx-log>
          <frame-events> .List </frame-events>
        </kmcd-driver>
  syntax MCDStep
  syntax MCDSteps  ::=
    ".MCDSteps"
  | MCDStep MCDSteps
  rule <k> .MCDSteps => . ... </k>
  rule <k> MCD:MCDStep MCDS:MCDSteps => MCD ~> MCDS ... </k>
  syntax MCDContract  ::=
    "contract" "(" MCDStep ")" [function, klabel(contract)]
  syntax Address  ::=
    Int
  | String
  | MCDContract
  syntax Event  ::=
    Transaction
  syntax Transaction  ::=
    ".Transaction" [klabel(.Transaction), symbol]
  | "Transaction" "(" acct: Address "," call: MCDStep "," events: List "," txException: Bool ")" [klabel(Transaction), symbol]
  syntax AdminStep  ::=
    "pushState"
  | "dropState"
  | "popState"
  | "assert"
endmodule

module KMCD
  imports KMCD-DRIVER
  configuration <kmcd>
        <kmcd-driver/>
      </kmcd>
endmodule

module KMCD-PROPS
  imports KMCD
  configuration <kmcd-properties>
          <kmcd/>
          <processed-events> .List </processed-events>
          <properties> .K </properties>
        </kmcd-properties>
endmodule

module KMCD-PRELUDE
  imports KMCD-PROPS
  syntax MCDStep  ::=
    "STEPS" "(" MCDSteps ")" [klabel(STEPS)]
  rule <k> STEPS ( MCDSTEPS ) => MCDSTEPS ... </k>
endmodule

module KMCD-GEN
  imports KMCD-PRELUDE
  imports BYTES
  configuration <kmcd-random>
        <kmcd-properties/>
        <kmcd-snapshots> .List </kmcd-snapshots>
        <kmcd-gen>
          <random> String2Bytes($RANDOMSEED:String) </random>
          <used-random> .Bytes </used-random>
          <generator-next> 0 </generator-next>
          <generator-current> 0 </generator-current>
          <generator-remainder> .K </generator-remainder>
          <generators>
            <generator multiplicity="*" type="Map">
              <generator-id> 0 </generator-id>
              <generator-steps> .K </generator-steps>
            </generator>
          </generators>
        </kmcd-gen>
      </kmcd-random>
endmodule
```

And input `spec-2.k`:

```
requires "kmcd-gen.k"

module VERIFICATION
    imports KMCD

    syntax KItem ::= runLemma ( Int ) | doneLemma ( Int )

    rule <k> runLemma(I) => doneLemma(I) ... </k>
endmodule

module SPEC-2
    imports VERIFICATION

    claim <k> runLemma(3 +Int 7) => doneLemma(10) ... </k>
endmodule
```

Reproduction Steps
------------------

```
$ kompile kmcd-gen.k --main-module KMCD-GEN --syntax-module KMCD-GEN --backend haskell
$ kprove spec-2.k -m VERIFICATION --debug
java.lang.NullPointerException
        at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
        at org.kframework.Collections$.mutable(collections.scala:30)
        at org.kframework.Collections.mutable(collections.scala)
        at org.kframework.compile.SortCells.nthArgSort(SortCells.java:877)
        at org.kframework.compile.SortCells.access$900(SortCells.java:63)
        at org.kframework.compile.SortCells$3.apply(SortCells.java:582)
        at org.kframework.compile.SortCells$3.apply(SortCells.java:567)
        at org.kframework.kore.KTransformer.apply(transformers.scala:11)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.kore.TransformK.apply(TransformK.java:41)
        at org.kframework.kore.TransformK.apply(TransformK.java:15)
        at org.kframework.kore.KTransformer.apply(transformers.scala:12)
        at org.kframework.kore.KTransformer.apply$(transformers.scala:10)
        at org.kframework.kore.AbstractKTransformer.apply(transformers.scala:123)
        at org.kframework.compile.SortCells.resolveIncompleteCellFragment(SortCells.java:693)
        at org.kframework.compile.SortCells.sortCells(SortCells.java:96)
        at org.kframework.compile.SortCells.sortCells(SortCells.java:115)
        at org.kframework.compile.ConcretizeCells.concretize(ConcretizeCells.java:75)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$3(transformers.scala:22)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:46)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.mutable.AbstractSet.map(Set.scala:46)
        at org.kframework.definition.ModuleTransformer$.$anonfun$fromSentenceTransformer$2(transformers.scala:20)
        at org.kframework.definition.ModuleTransformer.$anonfun$apply$1(transformers.scala:77)
        at scala.collection.concurrent.TrieMap.getOrElseUpdate(TrieMap.scala:903)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:74)
        at org.kframework.definition.ModuleTransformer.apply(transformers.scala:70)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:320)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:976)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike.map(SetLike.scala:101)
        at scala.collection.SetLike.map$(SetLike.scala:101)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at org.kframework.definition.DefinitionTransformer.apply(transformers.scala:114)
        at org.kframework.compile.ConcretizeCells.transformDefinition(ConcretizeCells.java:44)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:52)
        at org.kframework.backend.kore.KoreBackend.lambda$steps$14(KoreBackend.java:177)
        at org.kframework.kprove.ProofDefinitionBuilder.compileDefinition(ProofDefinitionBuilder.java:101)
        at org.kframework.kprove.ProofDefinitionBuilder.build(ProofDefinitionBuilder.java:80)
        at org.kframework.kprove.KProve.run(KProve.java:67)
        at org.kframework.kprove.KProveFrontEnd.run(KProveFrontEnd.java:59)
        at org.kframework.main.FrontEnd.main(FrontEnd.java:62)
        at org.kframework.main.Main.runApplication(Main.java:118)
        at org.kframework.main.Main.runApplication(Main.java:108)
        at org.kframework.main.Main.main(Main.java:56)
[Error] Internal: Uncaught exception thrown of type NullPointerException
(NullPointerException: null)
```

Expected Behavior
-----------------

Either the proof should go through, or a more informative error message should be posted telling me what's wrong with the definition.

### LINKED ISSUE #2024: [Bug] [kprove] - Reports macro symbol as a new constructor over `Int`
K Version
---------

```
$ kompile --version
K version:    5.1.61
Build date:   Thu Jun 10 21:12:51 UTC 2021
```

Description
-----------

When the `--def-module` for verification does _not_ include the `--main-module` from kompiling, and the `--main-module` contains a `macro` symbol, the prover incorrectly reports that macro symbol as a constructor.

Input Files
-----------

File `edsl.k` (note the macro `#ceil32`, contained in `EDSL` but in `EVM`):

```
requires "domains.md"

module EVM
    imports INT

    configuration <k> $PGM:Int </k>
endmodule

module EDSL
    imports EVM

    syntax Int ::= Int "up/Int" Int [function, no-evaluators]
 // ---------------------------------------------------------

    syntax Int ::= #ceil32 ( Int )
 // ------------------------------
    rule #ceil32(N) => (N up/Int 32) *Int 32 [macro]
endmodule
```

File `infinite-gas-spec.k` (note that we are importing `EVM`, not `EDSL`):

```
requires "edsl.k"

module VERIFICATION
    imports EVM

    syntax KItem ::= runLemma ( Step ) | doneLemma ( Step )
 // -------------------------------------------------------
    rule <k> runLemma(S) => doneLemma(S) ... </k>

    syntax Step ::= Bool
 // --------------------
 
endmodule

module INFINITE-GAS-SPEC
    imports VERIFICATION

    claim <k> runLemma(3 <Int 4) => doneLemma(true) ... </k>

endmodule
```

Reproduction Steps
------------------

Kompile the definition with the haskell backend and `--main-module EDSL`, then prove the definition with `--def-module` verification:

```
$ kompile --backend haskell edsl.k --main-module EDSL --syntax-module EDSL
$ kprove infinite-gas-spec.k --def-module VERIFICATION
[Error] Compiler: Cannot add new constructors to hooked sort Int
        Source(/home/dev/scratch/edsl.k)
        Location(15,20,15,34)
[Error] Compiler: Had 1 structural errors.
```

Expected Behavior
-----------------

The proof should go through. The error about the new constructor symbol should not be triggered for two reasons, (i) it's not a new constructor, it's a `macro`, and (ii) the module `EDSL` should not even be visible from the claims module or the `--def-module`.

### PR DESCRIPTION
**Pull request by radumereuta**
Fixes: #1333
Fixes: #1887
Fixes: #2024
This can be reviewed commit by commit.

The idea here is to minimize the work done by kprove, and reuse as much as possible from kompile. For that, I had to impose more strict checks which forbid rules and syntax in claim modules.

For the actual code, I made a copy of the existing java code into `kprovex` package and connected that to the new bash script:
- it was easier to make sure we have a clean code path compared to the old one
- in the future, if we want to diverge the functionality of the tools, we can do that easier

I've added a few integration tests and converted map-symbolic-tests-haskell to the new kprovex tool. The latter is 0.8s faster (kserver ; make -j 32) because it doesn't have to generate new definition.kore for each test.

### CODE REVIEW

**Comment by radumereuta** [comment]
regression-new/map-symbolic-tests-haskell
kserver ; time make proofs -j 32 -O -k --dry-run
master: 8.9s, kprovex: 7.9s

regression-new/map-symbolic-tests
kserver ; time make proofs -j 32 -O -k
master: 7.1s, kprovex: 7.2s

**Comment by ehildenb** [comment]
To test with KEVM: first checkout master branch of KEVM.

Then if you want the explicit full commands to use, add `set -x` to the top of the KEVM file. If you want ot use a global K install, do _not_ run the `make deps` step. Run `rm -rf .build` (or `make clean`) to remove previously installed submodules.

Make sure you set your PATH like `export PATH=.build/usr/bin:$PATH`.

If you change the `kevm` script, you need to run `make build` again.

To build a single example proof using new scheme:

```
kevm kompile tests/specs/mcd/functional-spec.k --backend haskell --backend-dir tests/specs/mcd --main-module FUNCTIONAL-SPEC-SYNTAX --syntax-module FUNCTIONAL-SPEC-SYNTAX -O2
```

Using `kevm kompile` causes it to include all the options needed for building KEVM correctly. Use the `set -x` above (and recall `make build -j8`) to see the actual call to `kompile` it makes.

Then to run a proof:

```
kevm prove tests/specs/mcd/functional-spec.k FUNCTIONAL-SPEC-SYNTAX --backend haskell --format-failures  --concrete-rules-file tests/specs/mcd/concrete-rules.txt --backend-dir tests/specs/mcd 
```

Then, modify the `kevm` script to use `kprovex` instead of `kprove` (need to call `make build -j8` again)

**Comment by ehildenb** [comment]
You probably only want to work with proofs that are passing on the Haskell backend. To list those, do `make test-prove TEST_SYMBOLIC_BACKEND=haskell --dry-run`.

**Comment by ehildenb** [comment]
If you want to hack it together to do all the proofs, you may be able to inject here https://github.com/kframework/evm-semantics/blob/master/kevm#L124

Something like this:

```
if [[ ! -d ${backend_dir}/*-kompiled ]]; then
    kevm kompile ...
fi

kprovex ...
```

Then you can just call `make test-prove TEST_SYMBOLIC_BACKEND=haskell`

**Comment by radumereuta** [comment]
I think I have some results. With some help from Everett, I managed to run some proofs with `kprove` and with `kprovex`
I had to call kompile in the spec subdir, with `--concrete-rules`. Then I run:
`time kevm prove tests/specs/mcd/vat-frob-diff-zero-dart-pass-rough-spec.k FUNCTIONAL-SPEC-SYNTAX --backend haskell --format-failures  --backend-dir tests/specs/mcd --dry-run`

| example                                                      | kprovex  | kprove |
| --------------------------------------------------------|-------------|---------- |
|  vat-frob-diff-zero-dart-pass-rough-spec.k  |  20s        | 26s     |
| vat-subui-pass-spec.k                                |  31.5s     |  39.8s |
| flopper-tick-pass-rough-spec.k                  |   22.3s    |  29.9s |

Right now the drop in time is because we don't rekompile the definition and we reuse `definition.kore`. But we still have some time to claim if we try to reuse the scanners. Maybe even more when I fine-tune Stopwatch measurements. Here is the output from kprovex:
```
$ time kevm prove tests/specs/mcd/flopper-tick-pass-rough-spec.k FUNCTIONAL-SPEC-SYNTAX --backend haskell --format-failures  --backend-dir tests/specs/mcd --dry-run
Parse command line options                                   =  0.011s
Importing: Source(/home/radu/work/evm-semantics/tests/specs/mcd/flopper-tick-pass-rough-spec.k)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/mcd/verification.k)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/lemmas.k)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/evm.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/data.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/evm-types.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/json-rpc.md)
Importing: Source(/home/radu/work/k/k-distribution/target/release/k/include/kframework/builtin/json.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/serialization.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/blockchain-k-plugin/include/kframework/krypto.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/network.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/edsl.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/buf.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/hashed-locations.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/abi.md)
Importing: Source(/home/radu/work/evm-semantics/.build/usr/lib/kevm/include/kframework/optimizations.md)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/mcd/bin_runtime.k)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/mcd/storage.k)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/infinite-gas.k)
Importing: Source(/home/radu/work/evm-semantics/tests/specs/mcd/word-pack.k)
New scanner: FUNCTIONAL-SPEC-SYNTAX-RULE-CELLS               =  1.174s
New scanner: FLOPPER-TICK-PASS-ROUGH-SPEC-RULE-CELLS         =  1.126s
Parse spec modules [2/2 rules]                               = 15.316s
kore-exec /home/radu/work/evm-semantics/./tests/specs/mcd/functional-spec-kompiled/definition.kore --module FUNCTIONAL-SPEC-SYNTAX --prove /home/radu/work/evm-semantics/./.kprove-2021-07-29-20-15-45-304-5e99f0ba-dd36-4e13-986f-5510abdfdee4/spec.kore --spec-module FLOPPER-TICK-PASS-ROUGH-SPEC --output /home/radu/work/evm-semantics/./.kprove-2021-07-29-20-15-45-304-5e99f0ba-dd36-4e13-986f-5510abdfdee4/result.kore
[Warning] Compiler: Variable 'VGas' defined but not used. Prefix variable name
with underscore if this is intentional.
	Source(/home/radu/work/evm-semantics/tests/specs/mcd/flopper-tick-pass-rough-spec.k)
	Location(30,24,30,28)
[Warning] Compiler: Variable 'ACCT_ID_ORIG_STORAGE' defined but not used.
Prefix variable name with underscore if this is intentional.
	Source(/home/radu/work/evm-semantics/tests/specs/mcd/flopper-tick-pass-rough-spec.k)
	Location(294,29,294,49)

real	0m22,330s
user	0m53,770s
sys	0m1,790s
```

File: kernel/src/main/java/org/kframework/kompile/Kompile.java [hunk 1]
```diff
@@ -284,6 +284,9 @@ private static Module excludeModulesByTag(Set<String> excludedModuleTags, Module
         DefinitionTransformer numberSentences = DefinitionTransformer.fromSentenceTransformer(NumberSentences::number, "number sentences uniquely");
         Function1<Definition, Definition> resolveConfigVar = d -> DefinitionTransformer.fromSentenceTransformer(new ResolveFunctionWithConfig(d, false)::resolveConfigVar, "Adding configuration variable to lhs").apply(d);
         Function1<Definition, Definition> resolveIO = (d -> Kompile.resolveIOStreams(kem, d));
+        Function1<Definition, Definition> markExtraConcreteRules = d -> DefinitionTransformer.fromSentenceTransformer((m, s) ->
```
Comment (dwightguth) [inline kernel/src/main/java/org/kframework/kompile/Kompile.java:287]: what is this for?

**Review by dwightguth — CHANGES_REQUESTED** [review]
I'm a little concerned about the call to `parseModules`, a function whose behavior doesn't seem to have been changed in any way. What's to stop `parseModules` from parsing files we require or import when we actually just want to parse the claims in the specification module with the preexisting grammar? The rest seems alright except I'm confused by this concrete thing. It seems like a separate change to me?

File: kernel/src/main/java/org/kframework/kompile/Kompile.java (hunk 1 above)
Comment (radumereuta) [reply kernel/src/main/java/org/kframework/kompile/Kompile.java:287]: This was a step from kprove that now needs to happen in kompile. (since we don't allow any modification to definition.kore)
All it does is add the attribute `concrete` to a specific set of rules that get interpreted differently by the backend.
This feature is used extensively by the EVM semantics.
It is now tested by `regression-new/concrete-function`

**Comment by radumereuta** [comment]
Going into `parseModules might need a separate PR. There are other issues that need to be considered (for example: #1890)
I know there are issues with that call:
```
New scanner: FUNCTIONAL-SPEC-SYNTAX-RULE-CELLS               =  1.174s
New scanner: FLOPPER-TICK-PASS-ROUGH-SPEC-RULE-CELLS         =  1.126s
```
We're building two scanners, even though we only need one. Pretty sure they are in sequence as well. We might even consider caching the scanners for kprovex if conditions are right. But that might be outside of the scope of this PR, which is already pretty big.

I think the next step would be to try and completely change a large definition to use kprovex and see how it behaves. At that point, I will also have a baseline to compare any further performance improvements.

**Comment by dwightguth** [comment]
I'm alright with further parsing change being in a future PR, but I would still like to understand what is going on with the concrete attribute.

**Review by dwightguth — APPROVED** [review]
looks good, but let's continue to iterate and improve further.
