### PR TITLE
Fix bug involving record production on rhs

### LINKED ISSUE #1318: Error for unbound variable doesn't specify source location
The following `kompile` error should report the offending line if possible.

```
[Error] Compiler: Found variable _ on right hand side of rule, not bound on left hand side. Did you mean "?_"?
[Error] Compiler: Had 1 structural errors.
```

Command:
```
kompile --backend llvm                                                    \
    --directory .build/defn/llvm -I .build/defn/llvm                                \
    --main-module WASM-TEST --syntax-module WASM-TEST-SYNTAX .build/defn/llvm/test.k
```

### PR DESCRIPTION
**Pull request by dwightguth**
Fixes #1318

### CODE REVIEW

File: kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala [hunk 1]
```diff
@@ -24,18 +24,18 @@ class TreeNodesToKORE(parseSort: java.util.function.Function[String, Sort], stri
...
 
   def termConsToKApply(t: TermCons): K = {
     if (t.production.att.contains("recordPrd", classOf[Production])) {
       val realProd = t.production.att.get("recordPrd", classOf[Production])
       val map = new util.ArrayList(t.items).asScala.reverse.zipWithIndex.map { case (item, idx) => (t.production.nonterminal(idx).name.get, apply(item))} toMap
       val realItems = realProd.nonterminals.map {
-        case NonTerminal(sort, None) => anonVar(sort)
-        case NonTerminal(sort, Some(x)) => map.getOrElse(x, anonVar(sort))
+        case NonTerminal(sort, None) => anonVar(sort, t)
+        case NonTerminal(sort, Some(x)) => map.getOrElse(x, anonVar(sort, t))
```
Comment (ehildenb) [inline kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala]: It's a little confusing to me that you're passing the entire `t: Term` into `anonVar`, because why would it need a term? Are you able to pass just the `Location` in for it to use? I'm approving anyway, but something to think about.

**Review by ehildenb — APPROVED** [review]

File: kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala (hunk 1 above)
Comment (dwightguth) [reply kore/src/main/scala/org/kframework/parser/TreeNodesToKORE.scala]: I changed the signature of the method to t: HasLocation to make it clearer what is happening.
