### PR TITLE
 kompile: add check for token sort productions

### LINKED ISSUE #2119: [kompile] should give more readable error message when rejecting token sorts with constructors
Right now we get a hard to read error message from the haskell backend, and a crash from the llvm backend:
```
module TEST
  syntax Foo ::= foo()
  syntax Foo ::= bam()
  syntax Foo ::= fu()
  syntax Foo ::= "bar" [token]
               | r"ba." [token, prec(3)]

  rule foo() => .K
  rule bam() => .K
  rule fu() => .K
  rule bar => .K
  rule baz => .K
endmodule

$ kompile test.k
[Error] Internal: Uncaught exception thrown of type MatchError.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues (MatchError:
(LiteralC(bar),Lblbam'LParRParUnds'TEST'Unds'Foo{}) (of class scala.Tuple2))

$ kompile test.k --backend haskell
Error:
  module 'TEST':
  symbol 'Lblbam'LParRParUnds'TEST'Unds'Foo' declaration (definition.kore 113:10):
    Cannot define constructor Lblbam'LParRParUnds'TEST'Unds'Foo for sort SortFoo{}: sort has domain values.
[Error] Critical: Haskell backend reported errors validating compiled
definition.
Examine output to see errors.
```

### PR DESCRIPTION
**Pull request by SchmErik**
Token sorts should only contain productions that have `token`,
`bracket`, or `function` labels or the RHS of the production is a macro
term. Any other label (including subsorts) are illegal.

The java backend is more forgiving when it comes to token sort
declarations. Avoid this check when kompile is running with the java
backend.

Fixes: #2119

### CODE REVIEW

File: kernel/src/main/java/org/kframework/kompile/Kompile.java [hunk 1]
```diff
@@ -437,6 +438,8 @@ public void structuralChecks(scala.collection.Set<Module> modules, Module mainMo
 
         stream(modules).forEach(m -> stream(m.localSentences()).forEach(new CheckHOLE(errors, m)::check));
 
+        stream(modules).forEach(m -> stream(m.localSentences()).forEach(new CheckTokens(errors, m, isSymbolic && isKast)::check));
```
Comment (radumereuta) [inline kernel/src/main/java/org/kframework/kompile/Kompile.java]: I think this check `isSymbolic && isKast` can be done before even entering this line.
So we would avoid this entire step instead of looking at each sentence and decide if we need to do something.

**Review by radumereuta — DISMISSED** [review]

File: kernel/src/main/java/org/kframework/kompile/Kompile.java [hunk 2]
```diff
@@ -437,6 +438,10 @@ public void structuralChecks(scala.collection.Set<Module> modules, Module mainMo
 
         stream(modules).forEach(m -> stream(m.localSentences()).forEach(new CheckHOLE(errors, m)::check));
 
+        if (!(isSymbolic && isKast)) {
```
Comment (radumereuta) [inline kernel/src/main/java/org/kframework/kompile/Kompile.java]:
```suggestion
        if (!(isSymbolic && isKast)) { // if it's not the java backend
```

**Review by radumereuta — APPROVED** [review]
