### PR TITLE
Anywhere is not supported by the haskell backend

### LINKED ISSUE #2909: [K-Bug] Expecting sort SortGeneratedTopCell but got SortK
### What component is the issue in?

_No response_

### Which command

- [x] kompile
- [ ] kast
- [ ] krun
- [ ] kprove
- [ ] kprovex
- [ ] ksearch

### What K Version?

K version:    5.3.205

### Operating System

Linux

#### `error.k`
```k
module ERROR-SYNTAX
  imports STRING

  syntax Error ::= "#exception" "(" String ")"
endmodule

module ERROR
  imports ERROR-SYNTAX
  imports BOOL

  rule [exception-non-ex]: true ~> #exception(_S:String) => .K [anywhere]
  rule [exception-exists]: false ~> #exception(S:String) => #exception(S) [anywhere]
endmodule
```

#### `test.k`
```k
requires "error.k"

module TEST
  imports ERROR
endmodule
```

### Steps to Reproduce

```shell
kompile test.k --backend haskell
```

### Expected Results

**now:**
kore-exec: [85986] Error (ErrorVerify):
    Error:
      module 'HCSP2SEQUENCE':
      alias 'rule0LHS' declaration (definition.kore 398:9):
      \and (definition.kore 400:10):
      (definition.kore 400:10, definition.kore 10:43):
        Expecting sort SortGeneratedTopCell{} but got SortK{}.
Created bug report: kore-exec.tar.gz
[Error] Critical: Haskell backend reported errors validating compiled
definition.
Examine output to see errors.

**exepected:**

**more info:** right after delete anywhere

### PR DESCRIPTION
**Pull request by radumereuta**
Fixes: #2909

### CODE REVIEW

File: kernel/src/main/java/org/kframework/kompile/Kompile.java [hunk 1]
```diff
@@ -459,6 +459,12 @@ public void proverChecksX(Module specModule, Module mainDefModule) {
     }
 
     public void structuralChecks(scala.collection.Set<Module> modules, Module mainModule, Option<Module> kModule, Set<String> excludedModuleTags) {
+        if (kompileOptions.backend.equals(Backends.HASKELL))
+            errors.addAll(stream(modules).flatMap(m -> stream(m.localSentences()).flatMap(s -> {
+                if (s instanceof Rule && s.att().contains(Att.ANYWHERE()))
+                    return Stream.of(KEMException.compilerError(Att.ANYWHERE() + " is not supported by the " + Backends.HASKELL + " backend.", s));
+                return Stream.empty();
+            })).collect(Collectors.toSet()));
```
Comment (Baltoli) [inline kernel/src/main/java/org/kframework/kompile/Kompile.java]: Could this be pulled out into its own function? I think it would be clearer following the style of the rest of the surrounding code

**Review by Baltoli — CHANGES_REQUESTED** [review]

File: kernel/src/main/java/org/kframework/kompile/Kompile.java (hunk 1 above)
Comment (radumereuta) [reply kernel/src/main/java/org/kframework/kompile/Kompile.java]: Fair point.

**Review by Baltoli — APPROVED** [review]
